### ISSUE TITLE
Add mage flags to the compiled mage binary

### ISSUE THREAD

**Issue by zbindenren** [magefile/mage#180]
When I run mage I can do the following:

```
mage -l
Targets:
  build      Builds the holidays binary.
  deps       Installs go dependencies.
  docker     Build Docker image.
  test       Run all go tests.
```

When I compile the mage file I do not have the mage flags anymore:

```
mage -compile mg
./mg -l
Unknown target specified: -l
./mg -v deps
Unknown target specified: -v
```
Would be great if one can still use the flagse (-v for example).

**Comment by natefinch** [comment]
Yup, that's a good point.   The compile to a specific binary feature was added late in the development, so it's kind of an afterthought (mostly because it was trivial to do so, since we're already compiling to a binary, we just let you specify which one with the flag). 

Adding support for flags to the compiled binary should be very easy.  The code for listing targets and running in verbose mode is already in the binary.  It just needs a tiny bit of code to handle the flags to set those.
