### ISSUE TITLE
Feature Request: automatic insertion of a job-scoped context

### ISSUE THREAD

**Issue by Xe** [magefile/mage#25]
This would allow for users to write functions like:

```go
func Build(ctx context.Context) error {
  cmd := exec.CommandContext(ctx, "/usr/local/go/bin/go", "build", "./cmd/...")
  cmd.Stdout = os.Stdout
  cmd.Stderr = os.Stderr
  err := cmd.Run()
}
```

And then if the user hits control-c to terminate the mage process, the context will instantly cancel and cause the process started by the `Build` function to be killed.

Mage itself would need to start and manage these contexts.

It would be nice to also have a command line flag `-t` that would set a timeout on these contexts.

**Comment by natefinch** [comment]
great idea! I had been contemplating allowing context, but hadn't thought about CLI specified timeouts. very cool.

**Comment by interlock** [comment]
We should figure out how to handle some common cases for this?

With a time for overall job complete, if a exec.ComandContext exceeds this time how do we signal to that job? What should we signal?

We may out grow a method signature that takes context.Context? Should we great a Mage struct that contains this and other future features? I am thinking about #24 right now.

`-t` applies to whole job or each job called? If we have many deps/build steps/network fetches it may make sense to limit total run time and/or job run time? Perhaps this is already solved with `Context.WithDeadline` and `Context.WithTimeout`?

@natefinch Thoughts on using `context.WithValue` ? Community seems split on it's use now, either: use only for values needed to cancel/deadline/manage context; or, use it for any sort value to this session/call/job/etc.

**Comment by natefinch** [comment]
I'd like to keep parameters as minimal as possible so that magefiles are easy to read and write.  An auto-populated context is fine, especially if it's opt-in.  A ton of other values gets too heavyweight for the writer and reader.

I really dislike context.WithValue.  That being said, the context should be used so people can put whatever they want in the context, because at the end of the day, it's just go code.

For example, this should be totally legal code:

```
func Build(ctx *context.Context) {
     ctx2 := ctx.WithValue(foo, bar)
     mg.Deps(ctx2, f, g)
}
```

Now as to whether we add official support for supplying values from the CLI or something, I don't know.  I don't think I would do it preemptively, for sure.

As for timeouts... I think to start, a simple timeout for the whole thing to run is sufficient.  If people start needing more complicated timeouts, we can think about it, but since I don't think make or rake support that kind of timeout, having anything will still put us ahead.
