### ISSUE TITLE
GitHub Action for Mage

### ISSUE THREAD

**Issue by crazy-max** [magefile/mage#305]
Hi @natefinch @StevenACoffman,

As I did for GoReleaser through goreleaser/goreleaser#1149, I thought that Mage should also benefit from its GitHub Action.

I have created a native [GitHub Action for Mage](https://github.com/crazy-max/ghaction-mage) using the [typescript-action](https://github.com/actions/typescript-action). This works on all [virtual environments](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources) supported by GitHub Actions. An integration workflow is [available](https://github.com/crazy-max/ghaction-mage/blob/master/.github/workflows/ci.yml) if you want to [take a look](https://github.com/crazy-max/ghaction-mage/runs/652722087?check_suite_focus=true#step:4:5).

Like I have done for [GoReleaser Action](https://github.com/goreleaser/goreleaser-action), I could transfer the repository here and open a PR to update the documentation.

Let me know if you are interested and thanks for this neat project!

**Comment by StevenACoffman** [comment]
Ha! I was just looking at that this morning! I was going to add it to https://github.com/magefile/awesome-mage

**Comment by crazy-max** [comment]
@StevenACoffman Ahah, hell of a coincidence!

**Comment by natefinch** [comment]
I appreciate the effort.  I'm curious, why a typescript action and not a Go action? My only concern is that not all go developers understand typescript.

**Comment by crazy-max** [comment]
@natefinch Today there are 3 ways to develop a GitHub Action. [Container Action](https://github.com/actions/container-action) (slow you have to pull and build a Docker image), [Javascript](https://github.com/actions/javascript-action) (native but not strict) or [Typescript](https://github.com/actions/typescript-action) (native and strict).

I'm also a Go developer and the choice was quick to choose the language to use for this GitHub Action. If you look at all the actions developed on GitHub, most of them use Typescript. If I had the choice I would have gone through Go for sure :)

**Comment by StevenACoffman** [comment]
Seth Vargo has [a good write-up](https://www.sethvargo.com/writing-github-actions-in-go/), but basically JavaScript github actions gets a full Node.js environment for free, where Docker github actions everything is BYO. Here's the tl;dr version:
### Pros and Cons
Using a Docker container for GitHub Actions has some benefits and drawbacks. Writing GitHub Actions in a different language and distributing them via a Docker container may not work for everyone.

#### Pros (of using Docker in Go for actions instead of Node.JS)
+ **Controlled execution environment** - if you need to modify the base system to install packages or libraries, the container primitive provides a predictable, reproducible, and customizable environment.
+ **Code in any language** - Since the Docker container includes the execution environment, use whatever programming language you prefer – C, Rust, Ruby, Python, Cobol, .NET – a world of possibilities await.
+ **Portable** - The container primitive is portable and can be used for more than GitHub Actions. docker pull the container locally and test it out locally.

#### Cons  (of using Docker in Go for actions instead of Node.JS)
+ **Bloat** - Crafting a slim Docker container is an art. As shown above, it can be challenging to create a small container. Big containers consume unnecessary bandwidth, eat up storage space, and pose a security risk.
+ **Complexity** - Adding the Dockerfile adds an additional layer of indirection between the code and the execution environment. For users who are no familiar with container technologies, this added complexity could be burdensome.
+ **Linux-only** - At the time of this writing, Docker-based GitHub Actions are only available on Linux builders. If you want to use a GitHub Action on Windows or Mac OS, you must use Node.js.

**Comment by natefinch** [comment]
That seems fair enough.  I don't know typescript at all, but it seems like the benefits are solid.

**Comment by crazy-max** [comment]
@natefinch Ok nice :)

About the migration to the org, for GoReleaser, @caarlos0 has created a dedicated [`github-action` team](https://github.com/orgs/goreleaser/teams) to let me manage the maintenance of the repo if it's good to you. This way I can handle releases on the [marketplace](https://github.com/marketplace?type=actions). Let me know when it's ok and I move the repo here and update the README with the same layout as you mage repo.

**Comment by crazy-max** [comment]
Ok @natefinch, I just received your invitation. I will prepare the migration and keep you in touch!

**Comment by crazy-max** [comment]
Repo moved and action available: https://github.com/magefile/mage-action 🎉
