### ISSUE TITLE
State of support of mage.

### ISSUE THREAD

**Issue by cep21** [magefile/mage#316]
Hi,

Mage is an interesting project and I'm trying to get a pulse of how modernly supported it is.  The only support channels I can view without logging in, linked from https://magefile.org/, are the twitter account, the blog, and the google group.  The twitter account, https://twitter.com/MagefileDotOrg, is last posted 2018.  The blog, https://magefile.org/blog/, is last posted 2018.  The google group, https://groups.google.com/g/magefile, is one post in 2019 without a response.

Support and news channels that are advertised and sparse or not up to date can be concerning.  I noticed a release in July (https://github.com/magefile/mage/releases) but there wasn't a post on the above mediums, for example.

Is it worth consolidating these various support channels, deprecating unused ones, or funneling people into a central place that can show activity for the project?

**Comment by mirogta** [comment]
Agree it would be nice to have the blog more recently updated and perhaps clarify/delete the google group.

- there are two active channels on Slack in gophers.slack.com - #mage and #mage-dev
- Twitter has recent posts, the latest is from 8 Jul 2020 (related to that release in July)... I can see this even in incognito mode when I'm not logged in to Twitter, so it's a bit confusing - where did you see the last post from 2018?

**Comment by natefinch** [comment]
It's actively supported :)   As mirogta mentioned, there was a post about the release here: https://twitter.com/MagefileDotOrg/status/1280968054994853893

The slack channels are where most people choose to ask questions.  
I must have missed the notification for the email from the google group... it's in my inbox, but unread.  And I don't go check the group very often since... as you saw, it's not used very much.  But I'll reply there so that it's obvious that it is still monitored.

**Comment by cep21** [comment]
Now I see the posts: I bet the major outage twitter had yesterday (https://twitter.com/TwitterSupport/status/1316880612691591174) was why I only saw posts from 2018.
