### ISSUE TITLE
TestGoModules fails in Go 1.16beta1

### ISSUE THREAD

**Issue by moorereason** [magefile/mage#329]
```
$ go version
go version go1.16beta1 linux/amd64

$ git log --oneline -1
07afc7d (HEAD -> master, tag: v1.11.0, origin/master, origin/HEAD) update release pipeline slightly (#327)

$ go test ./mage
...
--- FAIL: TestGoModules (0.10s)
    main_test.go:1445: exited with code 1.
        Stdout:
        Stderr: magefile.go:5:8: no required module provides package golang.org/x/text/unicode/norm; try 'go get -d golang.org/x/text/unicode/norm' to add it
        Error: error compiling magefiles
```
Skipped a bunch of debug output.  All other tests pass.  All tests pass with Go 1.15.6.

Can someone reproduce this?

**Comment by natefinch** [comment]
Thanks for bringing this up!

So, that test checks that if you're using go modules, you can run mage on a magefile with imports that aren't in your go.mod yet, and it'll still "just work". 

However, I remember they're changing something about `go get` etc in 1.16 so that how you install modules is a little different. I'll have to look it up and see what changes we might need to make.

**Comment by moorereason** [comment]
I'm assuming this is the relevant change from https://tip.golang.org/doc/go1.16#go-command:

> Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.
