### ISSUE TITLE
Error using Mage in non-module folder

### ISSUE THREAD

**Issue by mark-ross** [magefile/mage#338]
Hello,

Upon my recent upgrade to Go 1.16, I've found that the `mage` cli tool no longer works like it used to before the upgrade.

Basic project structure looks like this:
```
.
├── build.go
├── db
│   ├── dbconf.yml
│   └── migrations
└── webserver
    ├── go.mod
    ├── go.sum
    ├── main.go
    ├── site
    └── pkg
```

In the past, `mage` was able to interpret the `build.go` outside of a module to execute the scripts, but upon entering `mage` in the terminal to see my build commands, I get this error message (message has been a bit altered to remove any folder heirarchy):

```
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1: go: cannot find main module, but found .git/config in /project/directory
        to create a module there, run:
        go mod init
```

From a quick look through the source, I imagine the `strings.Contains` within the `Magefiles` function needs to include the new error message "cannot find _main_ module".  [This might be the file](https://github.com/magefile/mage/blob/4cf3cfcc82bab35b01ab1657c2aa2d0faeadac49/mage/main.go#L459).

Any suggestions or thoughts?

**Comment by natefinch** [comment]
This is because go modules default to on in 1.16.  previously, if you tried to build go where there was no go.mod, it would default to gopath mode.  But with 1.16 it doesn't do that anymore.  Which means mage will fail if there's no go.mod unless you manually set GO111MODULES=off ... but really that's only a temporary solution, because in go 1.17, I think they're getting rid of gopath mode entirely.

The long and the short of it is that you need a go.mod where your magefile is. it can be a mostly stub one - just run `go mod init mage` or whatever... it doesn't have to point to a real repo... but go needs that to build these days, unfortunately.

**Comment by mark-ross** [comment]
Excellent info. That worked.

For anyone looking at this, I did this in the base project next to my `build.go` file:
```
go mod init <proj>-build
go get github.com/magefile/mage/mg
go get github.com/magefile/mage/sh
```

Obviously, swap out `<proj>-build` with whatever you want.
Probably just need to `go get` any other dependencies for your build requirements.

Thanks for such a clear and quick response!
