### ISSUE TITLE
Unable to install via README.md instructions

### ISSUE THREAD

**Issue by whoisjake** [magefile/mage#88]
Running the recommended commands from the README.md:
```
go get -u -d github.com/magefile/mage
cd $GOPATH/src/github.com/magefile/mage
go run bootstrap.go
```
Getting:
```
Running target: Build
exec: git rev-parse --short HEAD
exec: git describe --tags
exec: go install -a -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-27T09:39:17-05:00" -X "github.com/magefile/mage/mage.commitHash=accd8ef" -X "github.com/magefile/mage/mage.gitTag=v2.0.1-3-gaccd8ef
" github.com/magefile/mage
go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied
Error: running "go install -a -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-27T09:39:17-05:00" -X "github.com/magefile/mage/mage.commitHash=accd8ef" -X "github.com/magefile/mage/mage.gitTag=v2.0.1-3-gaccd8ef
" github.com/magefile/mage" failed with exit code 1
exit status 1
```

macOS 10.12.6
```
$ go version
go version go1.9.2 darwin/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jake/Projects/Labs/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h2/whwtkkx168n8333397n69m2r0000gn/T/go-build684654678=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by natefinch** [comment]
`go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied`

This sounds like a bug in the go tooling.... I think it's trying to recompile the standard library.  I see several people complaining of similar problems when I google for permissions errors from go install -a.

What happens if you run `go install -a github.com/magefile/mage` without all the rest of the  nonsense?  I bet it still happens.

**Comment by natefinch** [comment]
Tracking this here: https://github.com/golang/go/issues/22469

For now, the fix is probably to use go build and then copy to your $GOPATH manually.

**Comment by whoisjake** [comment]
```
$ go install -a github.com/magefile/mage
go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied
```

**Comment by natefinch** [comment]
Thanks for confirming... i figured it was a problem just with the tooling, given the search results on the error.  I'll update the install script to avoid `go install -a` since it's evidently problematic when you have a system-installed version of go.  

Just to explain why I didn't see this - I built go from source on this machine, so it's able to rebuild my standard library without that error, since it lives in a user-editable directory).

Thanks for reporting this!  Definitely not a good first experience :)

**Comment by whoisjake** [comment]
No worries! Thanks for understanding go enough to know where to put this issue.

**Comment by natefinch** [comment]
pull again and try `go run bootstrap.go` again.  Let me know how it goes.

**Comment by whoisjake** [comment]
@natefinch worked like a charm. thanks!

**Comment by natefinch** [comment]
Awesome, thanks!
